### ISSUE TITLE
when trying to run on ios 7 it crashes

### ISSUE THREAD

**Issue by emadhegab** [norsez/BDDynamicGridViewController#12]
when trying to run on iOS 7 on xcode 4.5 it crashes with the following exception
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableViewCellScrollView gridContainerView]: unrecognized selector sent to instance

i investegate a little and i found that the method 
- (void)gesture:(UIGestureRecognizer_)gesture view:(UIView__)view viewIndex:(NSInteger_)viewIndex

is the one who have the problem when trying to iterate on 
cell.gridContainerView.subviews.count

the gridContainerView is nil.. but i don't know why that happen at all

**Comment by yesjun** [comment]
In iOS 7, New ScrollView has been added inside the table cell view hierarchy.
nebiros fixed this issue. ( https://github.com/nebiros/BDDynamicGridViewController/commit/54059aee985b654b0da69d5168f4c4b1b3e0e129 )
I prefer to use this code on line 383 in BDDynamicGridViewController.m:

``` Objective-C
BDDynamicGridCell *cell = (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_6_1) ? (BDDynamicGridCell*) [gesture.view.superview superview] : (BDDynamicGridCell*) [gesture.view.superview.superview superview];
```

**Comment by emadhegab** [comment]
yeah that went well

**Comment by norsez** [comment]
Awesome tip. Thank you.
