### ISSUE TITLE
it's crash when i click a picture

### ISSUE THREAD

**Issue by junhg521** [norsez/BDDynamicGridViewController#13]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableViewCellScrollView gridContainerView]: unrecognized selector sent to instance 0x895faf0'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0236e5e4 **exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x014cc8b6 objc_exception_throw + 44
    2   CoreFoundation                      0x0240b903 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
    3   CoreFoundation                      0x0235e90b ___forwarding_** + 1019
    4   CoreFoundation                      0x0235e4ee _CF_forwarding_prep_0 + 14
    5   BDDynamicGridViewDemo               0x00008194 -[BDDynamicGridViewController gesture:view:viewIndex:] + 388
    6   BDDynamicGridViewDemo               0x00008bd1 -[BDDynamicGridViewController didSingleTap:] + 161
    7   UIKit                               0x003a9f8c _UIGestureRecognizerSendActions + 230
    8   UIKit                               0x003a8c00 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 383
    9   UIKit                               0x003aa66d -[UIGestureRecognizer _delayedUpdateGesture] + 60
    10  UIKit                               0x003adbcd ___UIGestureRecognizerUpdate_block_invoke + 57
    11  UIKit                               0x003adb4e _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 317
    12  UIKit                               0x003a4248 _UIGestureRecognizerUpdate + 199
    13  CoreFoundation                      0x0233653e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
    14  CoreFoundation                      0x0233648f __CFRunLoopDoObservers + 399
    15  CoreFoundation                      0x023143b4 __CFRunLoopRun + 1076
    16  CoreFoundation                      0x02313b33 CFRunLoopRunSpecific + 467
    17  CoreFoundation                      0x0231394b CFRunLoopRunInMode + 123
    18  GraphicsServices                    0x022ca9d7 GSEventRunModal + 192
    19  GraphicsServices                    0x022ca7fe GSEventRun + 104
    20  UIKit                               0x0003294b UIApplicationMain + 1225
    21  BDDynamicGridViewDemo               0x00001c5d main + 141
    22  BDDynamicGridViewDemo               0x00001bc5 start + 53
    23  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nebiros** [comment]
@junhg521 I fix that in this pull request: https://github.com/norsez/BDDynamicGridViewController/pull/11, but @norsez seems like has been disappear, :-1:.
