### ISSUE TITLE
Version 0.0.5

### ISSUE THREAD

**Issue by nunofgs** [norsez/BDDynamicGridViewController#16]
Any chance you could release and tag a 0.0.5 version, as well as submit to the Cocoapods specs repository?

**Comment by norsez** [comment]
I can definitely do that. But not until September 1 when I am back from the road. I wouldn't mind if someone would take up the honor :)

**Comment by nunofgs** [comment]
I'm also on vacation until the 1st but I'd be happy to do it for you once I'm back.

Let's keep in touch.

**Comment by nunofgs** [comment]
Since Cocoapods now requires maintainers to push new versions, I can't submit a PR for this package.

Could you release the new version?

**Comment by norsez** [comment]
So sorry for late reply @nunofgs. Yes I can do that. Would you do me a favor? Cocoapods has changed a lot since last time I submitted it. Is there any current documentation on how to submit right now?

**Comment by nunofgs** [comment]
No problem. You can follow [this guide](http://guides.cocoapods.org/making/getting-setup-with-trunk.html) to setup your pod.

Then, when you're ready to release a new version, just do `pod trunk push file.podspec`.

**Comment by norsez** [comment]
I finally pushed 0.0.5 in. I am sorry I took five months to do it, @nunofgs. I can add your email as one of the owners if you like, just let me know which email address you prefer. Thanks!

**Comment by nunofgs** [comment]
No problem. I can definitely give you a hand maintaining the project if you like.

You can use the email I used on my commit. Just run `git log 5a58816 --pretty=full` to find it :)

**Comment by norsez** [comment]
Just added you as an owner of the pod trunk. Thanks so much, @nunofgs  :)
