### ISSUE TITLE
onSingleTab

### ISSUE THREAD

**Issue by ghass64** [norsez/BDDynamicGridViewController#18]
i tried to use it ,, so i can get the view and view index ,, but i can't understand how its work
can you please guide me !

**Comment by norsez** [comment]
Are you looks for the API method names or working sequence of the API?  Could you elaborate more please?

**Comment by ghass64** [comment]
no , am talking about to use this method (onSingleTab) for example:
 if i want to press one of the images i want to make action and to get the index of this image
for now am able to make action on press the image ,, but i need the index of this image by using this 
-(void (^)(UIView *, NSInteger))onSingleTap{}

**Comment by norsez** [comment]
The block, 

```
void(^)(UIView*, NSInteger)onSingleTap

```

should provide the index of the tapped view through its NSInteger parameter. Doesn't do that for you?

**Comment by ghass64** [comment]
no it doesn't provide me with anything ,,, it don't have parameter ,,its only pointer

**Comment by norsez** [comment]
Please try implementing the -onSingleTap like below in, say, -viewDidLoad

```
  self.onSingleTap = ^(UIView* view, NSInteger index) {
    NSLog(@"tap on %d", index);
  };
```

Then try running it, tap on a view and please let me know whether it prints out the view index.

**Comment by ghass64** [comment]
i tried it in all the possible controllers ,, but its not fired

**Comment by ghass64** [comment]
would you please push another commit that works and give the index of the image ?

**Comment by norsez** [comment]
Hi. Actually I did not create any fix. I only tried it in the demo project in the master branch on Github here. Maybe try a brand new clean check out? Xcode sometimes runs stale code and gets weird results.

**Comment by ghass64** [comment]
maybe you did not understand whats the problem exactly 
this block  :
void(^)(UIView*, NSInteger)onSingleTap

its triggered ,, but if i want to get the index the block should be something like this :
void(^)(UIView\* view, NSInteger index)onSingleTap

so i can get the index ,,, but its only nsinteger with no parameter ,, do you know how to get the index ,, at least just give me NSLOG syntax to get the index 

am really thankful for your help

**Comment by ghass64** [comment]
i found the problem ,,, your solution is work now ,,, i found that i was override the method onsingletap thats why it was not working 

thanks i will close this issue now

**Comment by norsez** [comment]
Cool. Glad it works now.
