### ISSUE TITLE
Layout breaks when coming back to the controller

### ISSUE THREAD

**Issue by tgallende** [norsez/BDDynamicGridViewController#19]
Hi,
When I press on one of the photos  of the gallery I load a new viewcontroller (push navigationcontroller). In this controller I show the picture and some info about it. The problem comes when I press the  back button (self.navigationcontroller pop....). I como back to the gallery but the layout is broken, some rows are over other ones. I'm testing in ios 8. Any idea why this can happen?
Thanks in advance.

**Comment by norsez** [comment]
Hi,

Is there any error log in the console? Also,if there's a screen capture, I would appreciate. 

Thanks,

n

**Comment by tgallende** [comment]
Hi,
Sorry, your code was perfect. The issue was produced by adding a top view with information in my app. I had to modify the frames for the table in bddynamicgridviewcontroller, and everything works OK when loading the controller for the first time.
The issue comes when coming back from a detail page, it seems to recalculate heights for every row and the layout is completely messed-in my case, not in your original code-.
Thanks a lot,

**Comment by norsez** [comment]
No problem. I am glad you had your problem sorted out. I'm closing this ticket now.
