### ISSUE TITLE
External images

### ISSUE THREAD

**Issue by pettersamuelsen** [norsez/BDDynamicGridViewController#4]
Which approach should I use to load external images into the grid? I have tried to both load the images with NSURLRequest as well as using the UIImageView+AFNetworking class (https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/UIImageView%2BAFNetworking.h), but no luck so far. 

Tips?

**Comment by norsez** [comment]
Hi Sorry for the late reply.

Could you please attach sample code of how you use UIImageView+AFNetworking class to load? So I can get a better picture.

**Comment by akaraca** [comment]
Hi norsez, thanks for this control. Can you also add a demo project for external images? I tried to use SDWebImage for pulling images from web and caching them, but had no luck with creating the imageView array.

**Comment by norsez** [comment]
@akaraca what trouble are you having with creating imageView array?

**Comment by akaraca** [comment]
Actually I managed that part, now it is downloading and caching images. I used UIImageView+Cache. Thanks a lot. :+1:
