### ISSUE TITLE
Every images using the same height?

### ISSUE THREAD

**Issue by kenpig** [norsez/BDDynamicGridViewController#5]
How to control each one of the images using the same height？ Could achieve delay loading？

**Comment by norsez** [comment]
Not sure what you mean by each image using the same height. The height is actually controlled by the underlying UITableView's row height delegate method. 

About delay loading, you can use the same technique as commonly used in UITableView.

**Comment by kenpig** [comment]
Thank you very much!ThanksKenpig在 2013-1-7，下午2:16，Norsez Orankijanan notifications@github.com 写道：Not sure what you mean by each image using the same height. The height is actually controlled by the underlying UITableView's row height delegate method. About delay loading, you can use the same technique as commonly used in UITableView.
