### ISSUE TITLE
if i load too many images it gets a little slow

### ISSUE THREAD

**Issue by emadhegab** [norsez/BDDynamicGridViewController#6]
i know it's crazy but i've putted 700 images and it got loaded a bit slow.. but when scrolling it was not smooth .. i'm trying to use lazytable  technique in it but i thought it would be better if you do it for all of us :)

**Comment by norsez** [comment]
I'll consider it if I find time. Thanks for your suggestion.

**Comment by emadhegab** [comment]
did you fixed it :)
